# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_blurring.ui'
#
# Created: Tue Aug  5 13:27:04 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Blurring(object):
    def setupUi(self, Blurring):
        Blurring.setObjectName(_fromUtf8("Blurring"))
        Blurring.setEnabled(True)
        Blurring.resize(694, 628)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Blurring.sizePolicy().hasHeightForWidth())
        Blurring.setSizePolicy(sizePolicy)
        Blurring.setFocusPolicy(QtCore.Qt.StrongFocus)
        Blurring.setWindowTitle(_fromUtf8("Blurring"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(Blurring)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.toolBox = QtGui.QToolBox(Blurring)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 676, 556))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox_blurredLayer = QtGui.QComboBox(self.page)
        self.comboBox_blurredLayer.setStatusTip(_fromUtf8(""))
        self.comboBox_blurredLayer.setWhatsThis(_fromUtf8(""))
        self.comboBox_blurredLayer.setAccessibleName(_fromUtf8(""))
        self.comboBox_blurredLayer.setAccessibleDescription(_fromUtf8(""))
        self.comboBox_blurredLayer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_blurredLayer.setMinimumContentsLength(11)
        self.comboBox_blurredLayer.setObjectName(_fromUtf8("comboBox_blurredLayer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_blurredLayer)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBox_radius = QtGui.QSpinBox(self.page)
        self.spinBox_radius.setMinimum(1)
        self.spinBox_radius.setMaximum(999999999)
        self.spinBox_radius.setSingleStep(50)
        self.spinBox_radius.setProperty("value", 1000)
        self.spinBox_radius.setObjectName(_fromUtf8("spinBox_radius"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_radius)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.checkBox_selectedFeatures = QtGui.QCheckBox(self.page)
        self.checkBox_selectedFeatures.setText(_fromUtf8(""))
        self.checkBox_selectedFeatures.setObjectName(_fromUtf8("checkBox_selectedFeatures"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBox_selectedFeatures)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.checkBox_addToMap = QtGui.QCheckBox(self.page)
        self.checkBox_addToMap.setText(_fromUtf8(""))
        self.checkBox_addToMap.setChecked(True)
        self.checkBox_addToMap.setObjectName(_fromUtf8("checkBox_addToMap"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBox_addToMap)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.groupBox_advanced = QgsCollapsibleGroupBox(self.page)
        self.groupBox_advanced.setObjectName(_fromUtf8("groupBox_advanced"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_advanced)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.groupBox_advanced)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.checkBox_exportRadius = QtGui.QCheckBox(self.frame)
        self.checkBox_exportRadius.setObjectName(_fromUtf8("checkBox_exportRadius"))
        self.verticalLayout.addWidget(self.checkBox_exportRadius)
        self.checkBox_exportCentroid = QtGui.QCheckBox(self.frame)
        self.checkBox_exportCentroid.setObjectName(_fromUtf8("checkBox_exportCentroid"))
        self.verticalLayout.addWidget(self.checkBox_exportCentroid)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.groupBox_advanced)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_envelope = QtGui.QCheckBox(self.frame_2)
        self.checkBox_envelope.setObjectName(_fromUtf8("checkBox_envelope"))
        self.horizontalLayout_3.addWidget(self.checkBox_envelope)
        self.comboBox_envelope = QtGui.QComboBox(self.frame_2)
        self.comboBox_envelope.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_envelope.setObjectName(_fromUtf8("comboBox_envelope"))
        self.horizontalLayout_3.addWidget(self.comboBox_envelope)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.groupBox_advanced)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_outputFile = QtGui.QLineEdit(self.page)
        self.lineEdit_outputFile.setEnabled(True)
        self.lineEdit_outputFile.setInputMask(_fromUtf8(""))
        self.lineEdit_outputFile.setText(_fromUtf8(""))
        self.lineEdit_outputFile.setObjectName(_fromUtf8("lineEdit_outputFile"))
        self.horizontalLayout.addWidget(self.lineEdit_outputFile)
        self.pushButton_browseFolder = QtGui.QPushButton(self.page)
        self.pushButton_browseFolder.setObjectName(_fromUtf8("pushButton_browseFolder"))
        self.horizontalLayout.addWidget(self.pushButton_browseFolder)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.pushButton_help = QtGui.QPushButton(self.page)
        self.pushButton_help.setObjectName(_fromUtf8("pushButton_help"))
        self.verticalLayout_4.addWidget(self.pushButton_help)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_ok = QtGui.QPushButton(self.page)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        spacerItem = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_cancel = QtGui.QPushButton(self.page)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.progressBar_progression = QtGui.QProgressBar(self.page)
        self.progressBar_progression.setProperty("value", 0)
        self.progressBar_progression.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_progression.setObjectName(_fromUtf8("progressBar_progression"))
        self.verticalLayout_4.addWidget(self.progressBar_progression)
        spacerItem1 = QtGui.QSpacerItem(17, 345, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 171, 91))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.comboBox_layerAlreadyBlurred = QtGui.QComboBox(self.page_2)
        self.comboBox_layerAlreadyBlurred.setObjectName(_fromUtf8("comboBox_layerAlreadyBlurred"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_layerAlreadyBlurred)
        self.comboBox_layer_statistics = QtGui.QComboBox(self.page_2)
        self.comboBox_layer_statistics.setObjectName(_fromUtf8("comboBox_layer_statistics"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_layer_statistics)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.buttonBox_stats = QtGui.QDialogButtonBox(self.page_2)
        self.buttonBox_stats.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_stats.setObjectName(_fromUtf8("buttonBox_stats"))
        self.verticalLayout_6.addWidget(self.buttonBox_stats)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.toolBox)

        self.retranslateUi(Blurring)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Blurring)

    def retranslateUi(self, Blurring):
        self.label.setToolTip(_translate("Blurring", "<html><head/><body><p>Layer which will be blurred</p></body></html>", None))
        self.label.setText(_translate("Blurring", "Point layer", None))
        self.comboBox_blurredLayer.setToolTip(_translate("Blurring", "Layer which will be blurred", None))
        self.label_2.setToolTip(_translate("Blurring", "Maximum radius", None))
        self.label_2.setText(_translate("Blurring", "Radius (map\'s unit)", None))
        self.spinBox_radius.setToolTip(_translate("Blurring", "Maximum radius", None))
        self.label_4.setText(_translate("Blurring", "Use only selected features", None))
        self.label_3.setText(_translate("Blurring", "Add result to canvas", None))
        self.groupBox_advanced.setTitle(_translate("Blurring", "Advanced", None))
        self.label_6.setText(_translate("Blurring", "Add to the attribute table :", None))
        self.checkBox_exportRadius.setText(_translate("Blurring", "the radius", None))
        self.checkBox_exportCentroid.setText(_translate("Blurring", "X and Y of centroid", None))
        self.checkBox_envelope.setText(_translate("Blurring", "Use envelope", None))
        self.label_5.setText(_translate("Blurring", "Output :", None))
        self.lineEdit_outputFile.setPlaceholderText(_translate("Blurring", "Save to temporary file", None))
        self.pushButton_browseFolder.setText(_translate("Blurring", "Browse", None))
        self.pushButton_help.setText(_translate("Blurring", "How my data are blurred ?", None))
        self.pushButton_ok.setText(_translate("Blurring", "OK", None))
        self.pushButton_cancel.setText(_translate("Blurring", "Cancel", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Blurring", "Blur a point layer", None))
        self.label_7.setText(_translate("Blurring", "Blurred layer", None))
        self.label_8.setText(_translate("Blurring", "Statistic layer", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Blurring", "Run statistics", None))

from qgis.gui import QgsCollapsibleGroupBox
