# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_blurring.ui'
#
# Created: Thu May 22 21:10:17 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Blurring(object):
    def setupUi(self, Blurring):
        Blurring.setObjectName(_fromUtf8("Blurring"))
        Blurring.setEnabled(True)
        Blurring.resize(426, 357)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Blurring.sizePolicy().hasHeightForWidth())
        Blurring.setSizePolicy(sizePolicy)
        Blurring.setFocusPolicy(QtCore.Qt.StrongFocus)
        Blurring.setWindowTitle(_fromUtf8("Blurring"))
        self.frame_2 = QtGui.QFrame(Blurring)
        self.frame_2.setGeometry(QtCore.QRect(430, 150, 351, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_envelope = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_envelope.setObjectName(_fromUtf8("checkBox_envelope"))
        self.horizontalLayout_3.addWidget(self.checkBox_envelope)
        self.comboBox_envelope = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_envelope.setObjectName(_fromUtf8("comboBox_envelope"))
        self.horizontalLayout_3.addWidget(self.comboBox_envelope)
        self.frame_3 = QtGui.QFrame(Blurring)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 411, 341))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.widget = QtGui.QWidget(self.frame_3)
        self.widget.setGeometry(QtCore.QRect(10, 10, 389, 103))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox_blurredLayer = QtGui.QComboBox(self.widget)
        self.comboBox_blurredLayer.setStatusTip(_fromUtf8(""))
        self.comboBox_blurredLayer.setWhatsThis(_fromUtf8(""))
        self.comboBox_blurredLayer.setAccessibleName(_fromUtf8(""))
        self.comboBox_blurredLayer.setAccessibleDescription(_fromUtf8(""))
        self.comboBox_blurredLayer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_blurredLayer.setMinimumContentsLength(11)
        self.comboBox_blurredLayer.setObjectName(_fromUtf8("comboBox_blurredLayer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_blurredLayer)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBox_radius = QtGui.QSpinBox(self.widget)
        self.spinBox_radius.setMinimum(1)
        self.spinBox_radius.setMaximum(999999999)
        self.spinBox_radius.setSingleStep(50)
        self.spinBox_radius.setProperty("value", 1000)
        self.spinBox_radius.setObjectName(_fromUtf8("spinBox_radius"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_radius)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.checkBox_selectedFeatures = QtGui.QCheckBox(self.widget)
        self.checkBox_selectedFeatures.setText(_fromUtf8(""))
        self.checkBox_selectedFeatures.setObjectName(_fromUtf8("checkBox_selectedFeatures"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.checkBox_selectedFeatures)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.checkBox_addToMap = QtGui.QCheckBox(self.widget)
        self.checkBox_addToMap.setText(_fromUtf8(""))
        self.checkBox_addToMap.setChecked(True)
        self.checkBox_addToMap.setObjectName(_fromUtf8("checkBox_addToMap"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBox_addToMap)
        self.widget1 = QtGui.QWidget(self.frame_3)
        self.widget1.setGeometry(QtCore.QRect(10, 120, 389, 51))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_outputFile = QtGui.QLineEdit(self.widget1)
        self.lineEdit_outputFile.setEnabled(True)
        self.lineEdit_outputFile.setInputMask(_fromUtf8(""))
        self.lineEdit_outputFile.setText(_fromUtf8(""))
        self.lineEdit_outputFile.setObjectName(_fromUtf8("lineEdit_outputFile"))
        self.horizontalLayout.addWidget(self.lineEdit_outputFile)
        self.pushButton_browseFolder = QtGui.QPushButton(self.widget1)
        self.pushButton_browseFolder.setObjectName(_fromUtf8("pushButton_browseFolder"))
        self.horizontalLayout.addWidget(self.pushButton_browseFolder)
        self.pushButton_advanced = QtGui.QPushButton(self.frame_3)
        self.pushButton_advanced.setGeometry(QtCore.QRect(10, 180, 389, 24))
        self.pushButton_advanced.setObjectName(_fromUtf8("pushButton_advanced"))
        self.widget2 = QtGui.QWidget(self.frame_3)
        self.widget2.setGeometry(QtCore.QRect(10, 240, 389, 51))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_ok = QtGui.QPushButton(self.widget2)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        spacerItem = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_cancel = QtGui.QPushButton(self.widget2)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.pushButton_help = QtGui.QPushButton(self.frame_3)
        self.pushButton_help.setGeometry(QtCore.QRect(10, 210, 389, 24))
        self.pushButton_help.setObjectName(_fromUtf8("pushButton_help"))
        self.progressBar_progression = QtGui.QProgressBar(self.frame_3)
        self.progressBar_progression.setGeometry(QtCore.QRect(10, 310, 389, 23))
        self.progressBar_progression.setProperty("value", 0)
        self.progressBar_progression.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_progression.setObjectName(_fromUtf8("progressBar_progression"))
        self.frame = QtGui.QFrame(Blurring)
        self.frame.setGeometry(QtCore.QRect(430, 10, 351, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 231, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.splitter = QtGui.QSplitter(self.frame)
        self.splitter.setGeometry(QtCore.QRect(10, 40, 188, 71))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.checkBox_exportRadius = QtGui.QCheckBox(self.splitter)
        self.checkBox_exportRadius.setObjectName(_fromUtf8("checkBox_exportRadius"))
        self.checkBox_exportCentroid = QtGui.QCheckBox(self.splitter)
        self.checkBox_exportCentroid.setObjectName(_fromUtf8("checkBox_exportCentroid"))

        self.retranslateUi(Blurring)
        QtCore.QMetaObject.connectSlotsByName(Blurring)

    def retranslateUi(self, Blurring):
        self.checkBox_envelope.setText(_translate("Blurring", "Use envelope", None))
        self.label.setToolTip(_translate("Blurring", "<html><head/><body><p>Layer which will be blurred</p></body></html>", None))
        self.label.setText(_translate("Blurring", "Point layer", None))
        self.comboBox_blurredLayer.setToolTip(_translate("Blurring", "Layer which will be blurred", None))
        self.label_2.setToolTip(_translate("Blurring", "Maximum radius", None))
        self.label_2.setText(_translate("Blurring", "Radius (map\'s unit)", None))
        self.spinBox_radius.setToolTip(_translate("Blurring", "Maximum radius", None))
        self.label_4.setText(_translate("Blurring", "Use only selected features", None))
        self.label_3.setText(_translate("Blurring", "Add result to canvas", None))
        self.label_5.setText(_translate("Blurring", "Output :", None))
        self.lineEdit_outputFile.setPlaceholderText(_translate("Blurring", "Save to temporary file", None))
        self.pushButton_browseFolder.setText(_translate("Blurring", "Browse", None))
        self.pushButton_advanced.setText(_translate("Blurring", "More options     >>>", None))
        self.pushButton_ok.setText(_translate("Blurring", "OK", None))
        self.pushButton_cancel.setText(_translate("Blurring", "Cancel", None))
        self.pushButton_help.setText(_translate("Blurring", "How my data are blurred ?", None))
        self.label_6.setText(_translate("Blurring", "Add to the attribute table :", None))
        self.checkBox_exportRadius.setText(_translate("Blurring", "the radius", None))
        self.checkBox_exportCentroid.setText(_translate("Blurring", "X and Y of centroid", None))

